package ir.miare.androidcodechallenge.data.di

import android.content.Context
import android.util.Log
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import ir.logicbase.mockfit.MockFitConfig
import ir.logicbase.mockfit.MockFitInterceptor
import ir.miare.androidcodechallenge.data.BASE_URL
import ir.miare.androidcodechallenge.data.network.FootballService
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.jackson.JacksonConverterFactory
import java.util.concurrent.TimeUnit
import javax.inject.Singleton

@InstallIn(SingletonComponent::class)
@Module
object NetworkModule {

    @Provides
    @Singleton
    fun providesJacksonConverter(): JacksonConverterFactory {
        return JacksonConverterFactory.create()
    }

    @Provides
    @Singleton
    fun provideMockFitInterceptor(
        @ApplicationContext context: Context
    ): MockFitInterceptor {
        return MockFitInterceptor(
            bodyFactory = { input -> context.resources.assets.open(input) },
            logger = { tag, message -> Log.d(tag, message) },
            baseUrl = "https://test_baseurl.com/v2/",
            requestPathToJsonMap = MockFitConfig.REQUEST_TO_JSON, // autogenerated constant, just press build button
            mockFilesPath = "",
            mockFitEnable = true,
            apiEnableMock = true,
            apiIncludeIntoMock = arrayOf(),
            apiExcludeFromMock = arrayOf(),
            apiResponseLatency = 1000L
        )
    }

    @Provides
    @Singleton
    fun provideOkHttpClient(
        mockFitInterceptor: MockFitInterceptor
    ): OkHttpClient {
        return OkHttpClient.Builder()
            .addInterceptor(mockFitInterceptor)
            .connectTimeout(20, TimeUnit.SECONDS)
            .writeTimeout(20, TimeUnit.SECONDS)
            .readTimeout(20, TimeUnit.SECONDS)
            .build()
    }

    @Provides
    @Singleton
    fun providesFootballService(
        okHttpClient: OkHttpClient, jacksonConverterFactory: JacksonConverterFactory
    ): FootballService {
        return Retrofit.Builder().baseUrl(BASE_URL)
            .addConverterFactory(jacksonConverterFactory)
            .client(okHttpClient)
            .build()
            .create(FootballService::class.java)

    }
}